export const SET_JOIN_INFO = 'SET_JOIN_INFO';
export const JOIN_FAILED = 'JOIN_FAILED';
export const JOIN_TIMEDOUT = 'JOIN_TIMEDOUT';
export const JOIN_RESET = 'JOIN_RESET';
export const SET_SECRET = 'SET_SECRET';
export const SET_USERNAME = 'SET_USERNAME';

export const SET_MESSAGE_TONE  = 'SET_MESSAGE_TONE';
export const GET_MESSAGE_TONE_FAILED = 'GET_MESSAGE_TONE_FAILED';
export const ADD_MESSAGE = 'ADD_MESSAGE';
export const SET_OTHER_USER = 'SET_OTHER_USER';
export const SEND_MESSAGE = 'SEND_MESSAGE';

